import { prisma } from './client';

type IconAsset = {
  slug: string;
  source: 'cuisinons' | 'openmoji';
  attribution: string;
};

const CATEGORY_ICONS: Record<string, IconAsset> = {
  VEGETABLES: { slug: 'cat-legumes', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  FRUITS: { slug: 'cat-fruits', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  STARCHES: { slug: 'cat-feculents', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  CEREALS: { slug: 'cat-cereales', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  LEGUMES: { slug: 'cat-legumineuses', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  MEATS: { slug: 'cat-viandes', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  FISH: { slug: 'cat-poissons', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  SEAFOOD: { slug: 'cat-fruits-de-mer', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  CHARCUTERIE: { slug: 'cat-charcuterie', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  EGGS: { slug: 'cat-oeufs', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  CHEESES: { slug: 'cat-fromages', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  DAIRY: { slug: 'cat-laitiers', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  FATS: { slug: 'cat-matieres-grasses', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  NUTS_SEEDS: { slug: 'cat-noix', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  SPICES: { slug: 'cat-epices', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  AROMATICS: { slug: 'cat-aromates', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  SAUCES: { slug: 'cat-sauces', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  CONDIMENTS: { slug: 'cat-condiments', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  PREPARATIONS: { slug: 'cat-preparations', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  BAKERY: { slug: 'cat-boulangerie', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  PASTRY: { slug: 'cat-patisserie', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  SUGARS: { slug: 'cat-sucres', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  BEVERAGES: { slug: 'cat-boissons', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  VEGETARIAN_PRODUCTS: { slug: 'cat-vegetarien', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  PROCESSED: { slug: 'cat-transformes', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
  OTHER: { slug: 'cat-autres', source: 'cuisinons', attribution: 'Illustration originale Cuisinons' },
};

/** Mots-clés -> illustration dédiée. Plusieurs centaines d'aliments Ciqual matchent ces clés. */
const DEDICATED_KEYWORDS: Array<[string, string]> = [
  ['poulet', 'poulet'],
  ['dinde', 'dinde'],
  ['boeuf', 'boeuf'],
  ['bœuf', 'boeuf'],
  ['steak', 'boeuf'],
  ['veau', 'veau'],
  ['porc', 'porc'],
  ['jambon', 'jambon'],
  ['lardon', 'lardon'],
  ['saucisse', 'saucisse'],
  ['agneau', 'agneau'],
  ['canard', 'canard'],
  ['saumon', 'saumon'],
  ['thon', 'thon'],
  ['cabillaud', 'cabillaud'],
  ['colin', 'cabillaud'],
  ['crevette', 'crevette'],
  ['moule', 'moule'],
  ['huitre', 'huitre'],
  ['huître', 'huitre'],
  ['oeuf', 'oeuf'],
  ['œuf', 'oeuf'],
  ['lait ', 'lait'],
  ['lait,', 'lait'],
  ['yaourt', 'yaourt'],
  ['skyr', 'skyr'],
  ['whey chocolat', 'chocolat'],
  ['whey vanille', 'vanille'],
  ['whey', 'fromage-blanc'],
  ['fromage blanc', 'fromage-blanc'],
  ['creme fraiche', 'creme'],
  ['crème fraîche', 'creme'],
  ['beurre', 'beurre'],
  ['huile d olive', "huile-olive"],
  ["huile d'olive", "huile-olive"],
  ['huile de tournesol', 'huile'],
  ['huile', 'huile'],
  ['emmental', 'fromage'],
  ['comté', 'fromage'],
  ['comte', 'fromage'],
  ['chevre', 'fromage'],
  ['chèvre', 'fromage'],
  ['mozzarella', 'fromage'],
  ['parmesan', 'fromage'],
  ['fromage', 'fromage'],
  ['riz', 'riz'],
  ['pates', 'pates'],
  ['pâtes', 'pates'],
  ['spaghetti', 'pates'],
  ['quinoa', 'quinoa'],
  ['avoine', 'avoine'],
  ['semoule', 'semoule'],
  ['pain', 'pain'],
  ['baguette', 'pain'],
  ['pomme de terre', 'pomme-de-terre'],
  ['patate douce', 'patate-douce'],
  ['carotte', 'carotte'],
  ['tomate', 'tomate'],
  ['oignon', 'oignon'],
  ['ail ', 'ail'],
  ['echalote', 'echalote'],
  ['échalote', 'echalote'],
  ['poireau', 'poireau'],
  ['courgette', 'courgette'],
  ['aubergine', 'aubergine'],
  ['poivron', 'poivron'],
  ['brocoli', 'brocoli'],
  ['chou-fleur', 'chou-fleur'],
  ['chou ', 'chou'],
  ['epinard', 'epinard'],
  ['épinard', 'epinard'],
  ['salade', 'salade'],
  ['laitue', 'salade'],
  ['concombre', 'concombre'],
  ['champignon', 'champignon'],
  ['haricot vert', 'haricot-vert'],
  ['petit pois', 'petit-pois'],
  ['mais', 'mais'],
  ['maïs', 'mais'],
  ['lentille', 'lentille'],
  ['pois chiche', 'pois-chiche'],
  ['haricot rouge', 'haricot-sec'],
  ['tofu', 'tofu'],
  ['pomme', 'pomme'],
  ['banane', 'banane'],
  ['fraise', 'fraise'],
  ['framboise', 'framboise'],
  ['myrtille', 'myrtille'],
  ['orange', 'orange'],
  ['citron', 'citron'],
  ['avocat', 'avocat'],
  ['mangue', 'mangue'],
  ['raisin', 'raisin'],
  ['poire', 'poire'],
  ['peche', 'peche'],
  ['pêche', 'peche'],
  ['abricot', 'abricot'],
  ['ananas', 'ananas'],
  ['kiwi', 'kiwi'],
  ['melon', 'melon'],
  ['pasteque', 'pasteque'],
  ['pastèque', 'pasteque'],
  ['amande', 'amande'],
  ['noix', 'noix'],
  ['noisette', 'noisette'],
  ['cacahuete', 'cacahuete'],
  ['cacahuète', 'cacahuete'],
  ['graine de chia', 'graines'],
  ['sesame', 'graines'],
  ['sésame', 'graines'],
  ['sucre', 'sucre'],
  ['miel', 'miel'],
  ['chocolat', 'chocolat'],
  ['cacao', 'cacao'],
  ['farine', 'farine'],
  ['levure', 'levure'],
  ['sel', 'sel'],
  ['poivre', 'poivre'],
  ['basilic', 'basilic'],
  ['persil', 'persil'],
  ['thym', 'thym'],
  ['ciboulette', 'ciboulette'],
  ['moutarde', 'moutarde'],
  ['vinaigre', 'vinaigre'],
  ['sauce soja', 'sauce-soja'],
  ['ketchup', 'ketchup'],
  ['mayonnaise', 'mayonnaise'],
  ['eau', 'eau'],
  ['cafe', 'cafe'],
  ['café', 'cafe'],
  ['the', 'the'],
  ['thé', 'the'],
  ['vin', 'vin'],
  ['biere', 'biere'],
  ['bière', 'biere'],
  ['lait de coco', 'lait-coco'],
  ['creme de coco', 'lait-coco'],
  ['gingembre', 'gingembre'],
  ['curry', 'epice'],
  ['paprika', 'epice'],
  ['cannelle', 'epice'],
  ['vanille', 'vanille'],
  ['yaourt grec', 'yaourt'],
  ['fromage râpé', 'fromage'],
  ['lard', 'lardon'],
  ['bacon', 'lardon'],
  ['merlu', 'cabillaud'],
  ['truite', 'truite'],
  ['sardine', 'sardine'],
  ['anchois', 'anchois'],
  ['calmar', 'calamar'],
  ['calamar', 'calamar'],
  ['fenouil', 'fenouil'],
  ['betterave', 'betterave'],
  ['celeri', 'celeri'],
  ['céleri', 'celeri'],
  ['navet', 'navet'],
  ['radis', 'radis'],
  ['asperge', 'asperge'],
  ['artichaut', 'artichaut'],
  ['potiron', 'potiron'],
  ['courge', 'potiron'],
  ['butternut', 'potiron'],
  ['patate', 'pomme-de-terre'],
];

function iconUrl(slug: string): string {
  return `/ingredients/${slug}.svg`;
}

export async function applyDedicatedIcons(): Promise<void> {
  const ingredients = await prisma.ingredient.findMany({
    select: { id: true, nameNormalized: true, nameFr: true, uxCategory: true, uxSubCategory: true },
  });

  for (const ingredient of ingredients) {
    const haystack = `${ingredient.nameNormalized} ${ingredient.nameFr.toLowerCase()}`;
    let dedicated: string | null = null;
    for (const [keyword, slug] of DEDICATED_KEYWORDS) {
      if (haystack.includes(keyword)) {
        dedicated = slug;
        break;
      }
    }
    const categoryIcon = CATEGORY_ICONS[ingredient.uxCategory] ?? CATEGORY_ICONS.OTHER;
    if (!categoryIcon) continue;
    if (dedicated) {
      await prisma.ingredient.update({
        where: { id: ingredient.id },
        data: {
          iconSlug: dedicated,
          iconUrl: iconUrl(dedicated),
          iconSource: 'cuisinons',
          iconAttribution: 'Illustration originale Cuisinons',
          dedicatedIcon: true,
        },
      });
    } else {
      await prisma.ingredient.update({
        where: { id: ingredient.id },
        data: {
          iconSlug: categoryIcon.slug,
          iconUrl: iconUrl(categoryIcon.slug),
          iconSource: categoryIcon.source,
          iconAttribution: categoryIcon.attribution,
          dedicatedIcon: false,
        },
      });
    }
  }
}

export { CATEGORY_ICONS, DEDICATED_KEYWORDS };
