/** Generated from scripts/ingredient-icon-catalog.json — do not edit by hand. */
export const DEDICATED_KEYWORDS: Array<[string, string]> = [
  ["copeaux de beurre de cacao", "cacao-beurre"],
  ["huile d'olive extra vierge", "huile-olive-extra"],
  ["huile de pépins de courge", "huile-de-pepin-de-courge"],
  ["huile de pépins de raisin", "huile-pepin-raisin"],
  ["fecule de pomme de terre", "fecule-de-pomme-de-terre"],
  ["fécule de pomme de terre", "fecule-de-pomme-de-terre"],
  ["fecule-de-pomme-de-terre", "fecule-de-pomme-de-terre"],
  ["huile de pepin de courge", "huile-de-pepin-de-courge"],
  ["huile-de-pepin-de-courge", "huile-de-pepin-de-courge"],
  ["pomme de terre grenaille", "pomme-de-terre-grenaille"],
  ["pomme-de-terre-grenaille", "pomme-de-terre-grenaille"],
  ["cereales petit dejeuner", "cereales-petit-dejeuner"],
  ["cereales-petit-dejeuner", "cereales-petit-dejeuner"],
  ["eau de fleur d oranger", "eau-de-fleur-d-oranger"],
  ["eau de fleur d'oranger", "eau-de-fleur-d-oranger"],
  ["eau-de-fleur-d-oranger", "eau-de-fleur-d-oranger"],
  ["maquereau au vin blanc", "maquereau-vin-blanc"],
  ["conserve de maquereau", "conserve-maquereau"],
  ["farine de pois chiche", "farine-pois-chiche"],
  ["groseille a maquereau", "groseille-a-maquereau"],
  ["groseille à maquereau", "groseille-a-maquereau"],
  ["groseille-a-maquereau", "groseille-a-maquereau"],
  ["moutarde a l ancienne", "moutarde-a-l-ancienne"],
  ["moutarde à l'ancienne", "moutarde-a-l-ancienne"],
  ["moutarde-a-l-ancienne", "moutarde-a-l-ancienne"],
  ["noix de cajou grillee", "noix-de-cajou-grillee"],
  ["noix de saint-jacques", "noix-saint-jacques"],
  ["noix-de-cajou-grillee", "noix-de-cajou-grillee"],
  ["tomate coeur de boeuf", "tomate-coeur-de-boeuf"],
  ["tomate-coeur-de-boeuf", "tomate-coeur-de-boeuf"],
  ["andouille de guemene", "andouille-de-guemene"],
  ["andouille de guémené", "andouille-de-guemene"],
  ["andouille-de-guemene", "andouille-de-guemene"],
  ["bouillon de volaille", "bouillon-de-volaille"],
  ["bouillon-de-volaille", "bouillon-de-volaille"],
  ["coeur de boeuf abats", "coeur-de-boeuf-abats"],
  ["coeur-de-boeuf-abats", "coeur-de-boeuf-abats"],
  ["colorant alimentaire", "colorant"],
  ["cornichon aigre-doux", "cornichon-aigre"],
  ["cuisse de grenouille", "cuisse-de-grenouille"],
  ["cuisse-de-grenouille", "cuisse-de-grenouille"],
  ["rillettes de poisson", "rillettes-poisson"],
  ["rouleau de printemps", "rouleau-de-printemps"],
  ["rouleau-de-printemps", "rouleau-de-printemps"],
  ["sauce worcestershire", "sauce-worcestershire"],
  ["sauce-worcestershire", "sauce-worcestershire"],
  ["saucisse de toulouse", "saucisse-de-toulouse"],
  ["saucisse-de-toulouse", "saucisse-de-toulouse"],
  ["vin blanc de cuisine", "vin-blanc-cuisine"],
  ["vin rouge de cuisine", "vin-rouge-cuisine"],
  ["beurre de cacahuete", "beurre-de-cacahuete"],
  ["beurre de cacahuète", "beurre-de-cacahuete"],
  ["beurre-de-cacahuete", "beurre-de-cacahuete"],
  ["caramel beurre sale", "caramel-beurre-sale"],
  ["caramel beurre salé", "caramel-beurre-sale"],
  ["caramel-beurre-sale", "caramel-beurre-sale"],
  ["champignon de paris", "champignon-paris"],
  ["chausson aux pommes", "chausson-aux-pommes"],
  ["chausson-aux-pommes", "chausson-aux-pommes"],
  ["concentre de tomate", "concentre-de-tomate"],
  ["concentré de tomate", "concentre-de-tomate"],
  ["concentre-de-tomate", "concentre-de-tomate"],
  ["confiture d'abricot", "confiture-abricot"],
  ["conserve de sardine", "conserve-sardine"],
  ["fruit de la passion", "fruit-de-la-passion"],
  ["fruit-de-la-passion", "fruit-de-la-passion"],
  ["galette de sarrasin", "galette-sarrasin"],
  ["graine de coriandre", "coriandre-graine"],
  ["graine de tournesol", "graine-de-tournesol"],
  ["graine-de-tournesol", "graine-de-tournesol"],
  ["levure de boulanger", "levure-boulanger"],
  ["maquereau vin blanc", "maquereau-vin-blanc"],
  ["maquereau-vin-blanc", "maquereau-vin-blanc"],
  ["miel de chataignier", "miel-de-chataignier"],
  ["miel de châtaignier", "miel-de-chataignier"],
  ["miel-de-chataignier", "miel-de-chataignier"],
  ["pate de curry rouge", "pate-de-curry-rouge"],
  ["pâte de curry rouge", "pate-de-curry-rouge"],
  ["pâte de curry verte", "pate-de-curry-vert"],
  ["pate-de-curry-rouge", "pate-de-curry-rouge"],
  ["saucisse de morteau", "saucisse-de-morteau"],
  ["saucisse-de-morteau", "saucisse-de-morteau"],
  ["tomate cœur de bœuf", "tomate-coeur-de-boeuf"],
  ["vinaigre balsamique", "vinaigre-balsamique"],
  ["vinaigre-balsamique", "vinaigre-balsamique"],
  ["yaourt a la grecque", "yaourt-a-la-grecque"],
  ["yaourt à la grecque", "yaourt-a-la-grecque"],
  ["yaourt-a-la-grecque", "yaourt-a-la-grecque"],
  ["betterave chioggia", "betterave-chioggia"],
  ["betterave-chioggia", "betterave-chioggia"],
  ["boulette de viande", "boulette"],
  ["cassonade complete", "cassonade-complete"],
  ["cassonade-complete", "cassonade-complete"],
  ["caviar d aubergine", "caviar-d-aubergine"],
  ["caviar d'aubergine", "caviar-d-aubergine"],
  ["caviar-d-aubergine", "caviar-d-aubergine"],
  ["concombre libanais", "concombre-libanais"],
  ["concombre-libanais", "concombre-libanais"],
  ["conserve maquereau", "conserve-maquereau"],
  ["conserve-maquereau", "conserve-maquereau"],
  ["côtelette d'agneau", "cotelette-agneau"],
  ["escalope milanaise", "escalope-milanaise"],
  ["escalope-milanaise", "escalope-milanaise"],
  ["farine de sarrasin", "farine-sarrasin"],
  ["farine pois chiche", "farine-pois-chiche"],
  ["farine-pois-chiche", "farine-pois-chiche"],
  ["feuille de laurier", "feuille-de-laurier"],
  ["feuille-de-laurier", "feuille-de-laurier"],
  ["graine de moutarde", "moutarde-graine"],
  ["herbes de provence", "herbes-de-provence"],
  ["herbes-de-provence", "herbes-de-provence"],
  ["huile de tournesol", "huile-tournesol"],
  ["huile pepin raisin", "huile-pepin-raisin"],
  ["huile-pepin-raisin", "huile-pepin-raisin"],
  ["mousse au chocolat", "mousse-chocolat"],
  ["noix de coco rapee", "noix-de-coco-rapee"],
  ["noix de coco râpée", "noix-de-coco-rapee"],
  ["noix saint jacques", "noix-saint-jacques"],
  ["noix-de-coco-rapee", "noix-de-coco-rapee"],
  ["noix-saint-jacques", "noix-saint-jacques"],
  ["oignon au vinaigre", "oignon-pickle"],
  ["pate de curry vert", "pate-de-curry-vert"],
  ["pate-de-curry-vert", "pate-de-curry-vert"],
  ["pépite de chocolat", "pepite-chocolat"],
  ["piment d'espelette", "piment-espelette"],
  ["piment doux graine", "piment-doux-graine"],
  ["piment-doux-graine", "piment-doux-graine"],
  ["pomme granny smith", "pomme-granny"],
  ["prune reine claude", "prune-reine-claude"],
  ["prune-reine-claude", "prune-reine-claude"],
  ["velouté de potiron", "veloute-potiron"],
  ["anchois à l'huile", "anchois-huile"],
  ["baie de genevrier", "baie-de-genevrier"],
  ["baie de genévrier", "baie-de-genevrier"],
  ["baie-de-genevrier", "baie-de-genevrier"],
  ["barre de céréales", "barre-cereales"],
  ["chou de bruxelles", "chou-de-bruxelles"],
  ["chou fleur violet", "chou-fleur-violet"],
  ["chou-de-bruxelles", "chou-de-bruxelles"],
  ["chou-fleur violet", "chou-fleur-violet"],
  ["chou-fleur-violet", "chou-fleur-violet"],
  ["confiture abricot", "confiture-abricot"],
  ["confiture-abricot", "confiture-abricot"],
  ["crottin de chèvre", "crottin"],
  ["feuille de kaffir", "feuille-de-kaffir"],
  ["feuille-de-kaffir", "feuille-de-kaffir"],
  ["figue de barbarie", "figue-de-barbarie"],
  ["figue-de-barbarie", "figue-de-barbarie"],
  ["graine de fenouil", "fenouil-graine"],
  ["graisse de canard", "graisse-de-canard"],
  ["graisse-de-canard", "graisse-de-canard"],
  ["gratin dauphinois", "gratin-dauphinois"],
  ["gratin-dauphinois", "gratin-dauphinois"],
  ["hachis parmentier", "hachis-parmentier"],
  ["hachis-parmentier", "hachis-parmentier"],
  ["haricot flageolet", "haricot-flageolet"],
  ["haricot-flageolet", "haricot-flageolet"],
  ["huile de cameline", "huile-cameline"],
  ["huile de noisette", "huile-de-noisette"],
  ["huile de pistache", "huile-de-pistache"],
  ["huile olive extra", "huile-olive-extra"],
  ["huile-de-noisette", "huile-de-noisette"],
  ["huile-de-pistache", "huile-de-pistache"],
  ["huile-olive-extra", "huile-olive-extra"],
  ["jambon de bayonne", "jambon-de-bayonne"],
  ["jambon-de-bayonne", "jambon-de-bayonne"],
  ["liqueur de cassis", "liqueur-de-cassis"],
  ["liqueur-de-cassis", "liqueur-de-cassis"],
  ["noix de macadamia", "noix-de-macadamia"],
  ["noix-de-macadamia", "noix-de-macadamia"],
  ["pain aux cereales", "pain-aux-cereales"],
  ["pain aux céréales", "pain-aux-cereales"],
  ["pain-aux-cereales", "pain-aux-cereales"],
  ["piment de cayenne", "piment-cayenne"],
  ["poivre de sichuan", "poivre-sichuan"],
  ["proteine vegetale", "proteine-vegetale"],
  ["protéine végétale", "proteine-vegetale"],
  ["proteine-vegetale", "proteine-vegetale"],
  ["puree de noisette", "puree-de-noisette"],
  ["purée de noisette", "puree-de-noisette"],
  ["puree-de-noisette", "puree-de-noisette"],
  ["rillettes poisson", "rillettes-poisson"],
  ["rillettes-poisson", "rillettes-poisson"],
  ["sardine à l'huile", "sardine-huile"],
  ["sauce aigre douce", "sauce-aigre-douce"],
  ["sauce aigre-douce", "sauce-aigre-douce"],
  ["sauce soja sucree", "sauce-soja-sucree"],
  ["sauce soja sucrée", "sauce-soja-sucree"],
  ["sauce-aigre-douce", "sauce-aigre-douce"],
  ["sauce-soja-sucree", "sauce-soja-sucree"],
  ["veau à blanquette", "blanquette"],
  ["vin blanc cuisine", "vin-blanc-cuisine"],
  ["vin rouge cuisine", "vin-rouge-cuisine"],
  ["vin-blanc-cuisine", "vin-blanc-cuisine"],
  ["vin-rouge-cuisine", "vin-rouge-cuisine"],
  ["vinaigre de cidre", "vinaigre-cidre"],
  ["vinaigre de xérès", "vinaigre-xeres"],
  ["bloc de saindoux", "saindoux-bloc"],
  ["bœuf bourguignon", "bourguignon"],
  ["boisson vegetale", "boisson-vegetale"],
  ["boisson végétale", "boisson-vegetale"],
  ["boisson-vegetale", "boisson-vegetale"],
  ["carotte violette", "carotte-violette"],
  ["carotte-violette", "carotte-violette"],
  ["champignon paris", "champignon-paris"],
  ["champignon-paris", "champignon-paris"],
  ["chocolat au lait", "chocolat-lait"],
  ["coeur de palmier", "coeur-de-palmier"],
  ["coeur-de-palmier", "coeur-de-palmier"],
  ["confit de canard", "confit-de-canard"],
  ["confit-de-canard", "confit-de-canard"],
  ["conserve de thon", "conserve-thon"],
  ["conserve sardine", "conserve-sardine"],
  ["conserve-sardine", "conserve-sardine"],
  ["coriandre graine", "coriandre-graine"],
  ["coriandre-graine", "coriandre-graine"],
  ["cotelette agneau", "cotelette-agneau"],
  ["cotelette-agneau", "cotelette-agneau"],
  ["coulis de fruits", "coulis-fruits"],
  ["coulis de tomate", "coulis-tomate"],
  ["courge spaghetti", "courge-spaghetti"],
  ["courge-spaghetti", "courge-spaghetti"],
  ["creme de gruyere", "creme-de-gruyere"],
  ["crème de gruyère", "creme-de-gruyere"],
  ["creme patissiere", "creme-patissiere"],
  ["crème pâtissière", "creme-patissiere"],
  ["creme-de-gruyere", "creme-de-gruyere"],
  ["creme-patissiere", "creme-patissiere"],
  ["cube de bouillon", "cube-bouillon"],
  ["cuisse de poulet", "cuisse-de-poulet"],
  ["cuisse-de-poulet", "cuisse-de-poulet"],
  ["escalope de veau", "escalope-veau"],
  ["farine de seigle", "farine-seigle"],
  ["flocons d avoine", "flocons-d-avoine"],
  ["flocons d'avoine", "flocons-d-avoine"],
  ["flocons-d-avoine", "flocons-d-avoine"],
  ["foie de volaille", "foie-de-volaille"],
  ["foie-de-volaille", "foie-de-volaille"],
  ["fromage à fondue", "fondue"],
  ["fumet de poisson", "fumet-de-poisson"],
  ["fumet-de-poisson", "fumet-de-poisson"],
  ["galette des rois", "galette-des-rois"],
  ["galette sarrasin", "galette-sarrasin"],
  ["galette-des-rois", "galette-des-rois"],
  ["galette-sarrasin", "galette-sarrasin"],
  ["graine d'edamame", "edamame-graine"],
  ["graine de courge", "graine-de-courge"],
  ["graine de piment", "piment-doux-graine"],
  ["graine de sesame", "graine-de-sesame"],
  ["graine de sésame", "graine-de-sesame"],
  ["graine-de-courge", "graine-de-courge"],
  ["graine-de-sesame", "graine-de-sesame"],
  ["huile d'arachide", "huile-arachide"],
  ["lait de noisette", "lait-de-noisette"],
  ["lait demi ecreme", "lait-demi-ecreme"],
  ["lait demi-écrémé", "lait-demi-ecreme"],
  ["lait-de-noisette", "lait-de-noisette"],
  ["lait-demi-ecreme", "lait-demi-ecreme"],
  ["levure boulanger", "levure-boulanger"],
  ["levure-boulanger", "levure-boulanger"],
  ["magret de canard", "magret"],
  ["mélange d'épices", "epice"],
  ["melange etudiant", "melange-etudiant"],
  ["mélange étudiant", "melange-etudiant"],
  ["melange-etudiant", "melange-etudiant"],
  ["melon charentais", "melon-charentais"],
  ["melon-charentais", "melon-charentais"],
  ["moule de bouchot", "moule-de-bouchot"],
  ["moule-de-bouchot", "moule-de-bouchot"],
  ["nugget de poulet", "nugget"],
  ["oeufs de poisson", "oeufs-de-poisson"],
  ["oeufs-de-poisson", "oeufs-de-poisson"],
  ["pain au chocolat", "pain-au-chocolat"],
  ["pain-au-chocolat", "pain-au-chocolat"],
  ["pate de campagne", "pate-de-campagne"],
  ["pâté de campagne", "pate-de-campagne"],
  ["pate-de-campagne", "pate-de-campagne"],
  ["perle de tapioca", "perle-de-tapioca"],
  ["perle-de-tapioca", "perle-de-tapioca"],
  ["petit pois casse", "petit-pois-casse"],
  ["petit pois cassé", "petit-pois-casse"],
  ["petit-pois-casse", "petit-pois-casse"],
  ["piment espelette", "piment-espelette"],
  ["piment-espelette", "piment-espelette"],
  ["plat de couscous", "couscous-plat"],
  ["pousse de bambou", "pousse-bambou"],
  ["proteine de soja", "proteine-de-soja"],
  ["protéine de soja", "proteine-de-soja"],
  ["proteine-de-soja", "proteine-de-soja"],
  ["puree de carotte", "puree-de-carotte"],
  ["purée de carotte", "puree-de-carotte"],
  ["puree-de-carotte", "puree-de-carotte"],
  ["sauce bolognaise", "sauce-bolognaise"],
  ["sauce-bolognaise", "sauce-bolognaise"],
  ["saucisse hot-dog", "hot-dog"],
  ["sirop de glucose", "sirop-de-glucose"],
  ["sirop-de-glucose", "sirop-de-glucose"],
  ["soupe a l oignon", "soupe-a-l-oignon"],
  ["soupe à l'oignon", "soupe-a-l-oignon"],
  ["soupe-a-l-oignon", "soupe-a-l-oignon"],
  ["stévia en poudre", "stevia-poudre"],
  ["araignee de mer", "araignee-de-mer"],
  ["araignée de mer", "araignee-de-mer"],
  ["araignee-de-mer", "araignee-de-mer"],
  ["asperge blanche", "asperge-blanche"],
  ["asperge-blanche", "asperge-blanche"],
  ["banane plantain", "banane-plantain"],
  ["banane-plantain", "banane-plantain"],
  ["barre proteinee", "barre-proteinee"],
  ["barre protéinée", "barre-proteinee"],
  ["barre-proteinee", "barre-proteinee"],
  ["beurre clarifie", "beurre-clarifie"],
  ["beurre clarifié", "beurre-clarifie"],
  ["beurre de cacao", "beurre-de-cacao"],
  ["beurre-clarifie", "beurre-clarifie"],
  ["beurre-de-cacao", "beurre-de-cacao"],
  ["blanc de poulet", "blanc-de-poulet"],
  ["blanc-de-poulet", "blanc-de-poulet"],
  ["bleu d auvergne", "bleu-d-auvergne"],
  ["bleu d'auvergne", "bleu-d-auvergne"],
  ["bleu-d-auvergne", "bleu-d-auvergne"],
  ["brocoli chinois", "brocoli-chinois"],
  ["brocoli-chinois", "brocoli-chinois"],
  ["cacao en poudre", "cacao-en-poudre"],
  ["cacao non sucré", "cacao-en-poudre"],
  ["cacao-en-poudre", "cacao-en-poudre"],
  ["chou à la crème", "choux"],
  ["clou de girofle", "clou-de-girofle"],
  ["clou-de-girofle", "clou-de-girofle"],
  ["cœur de palmier", "coeur-de-palmier"],
  ["confit d oignon", "confit-d-oignon"],
  ["confit d'oignon", "confit-d-oignon"],
  ["confit-d-oignon", "confit-d-oignon"],
  ["cornichon aigre", "cornichon-aigre"],
  ["cornichon-aigre", "cornichon-aigre"],
  ["courgette jaune", "courgette-jaune"],
  ["courgette-jaune", "courgette-jaune"],
  ["crème de cassis", "liqueur-de-cassis"],
  ["creme de marron", "creme-de-marron"],
  ["crème de marron", "creme-de-marron"],
  ["creme-de-marron", "creme-de-marron"],
  ["épaule d'agneau", "epaule-agneau"],
  ["extrait de malt", "extrait-de-malt"],
  ["extrait-de-malt", "extrait-de-malt"],
  ["farine complete", "farine-complete"],
  ["farine complète", "farine-complete"],
  ["farine sarrasin", "farine-sarrasin"],
  ["farine-complete", "farine-complete"],
  ["farine-sarrasin", "farine-sarrasin"],
  ["flocons de mais", "flocons-de-mais"],
  ["flocons de maïs", "flocons-de-mais"],
  ["flocons-de-mais", "flocons-de-mais"],
  ["fourme d ambert", "fourme-d-ambert"],
  ["fourme d'ambert", "fourme-d-ambert"],
  ["fourme-d-ambert", "fourme-d-ambert"],
  ["fraise des bois", "fraise-des-bois"],
  ["fraise-des-bois", "fraise-des-bois"],
  ["fruit du dragon", "fruit-du-dragon"],
  ["fruit-du-dragon", "fruit-du-dragon"],
  ["graine de pavot", "pavot"],
  ["haricot tarbais", "tarbais"],
  ["huile de sésame", "huile-sesame"],
  ["huile tournesol", "huile-tournesol"],
  ["huile-tournesol", "huile-tournesol"],
  ["jambon iberique", "jambon-iberique"],
  ["jambon ibérique", "jambon-iberique"],
  ["jambon-iberique", "jambon-iberique"],
  ["langue de boeuf", "langue-de-boeuf"],
  ["langue-de-boeuf", "langue-de-boeuf"],
  ["lentille beluga", "lentille-beluga"],
  ["lentille corail", "lentille-corail"],
  ["lentille du puy", "lentille-puy"],
  ["lentille-beluga", "lentille-beluga"],
  ["lentille-corail", "lentille-corail"],
  ["levure chimique", "levure-chimique"],
  ["levure de biere", "levure-de-biere"],
  ["levure de bière", "levure-de-biere"],
  ["levure-chimique", "levure-chimique"],
  ["levure-de-biere", "levure-de-biere"],
  ["mousse chocolat", "mousse-chocolat"],
  ["mousse-chocolat", "mousse-chocolat"],
  ["moutarde graine", "moutarde-graine"],
  ["moutarde-graine", "moutarde-graine"],
  ["nouilles de riz", "nouilles-riz"],
  ["œufs de poisson", "oeufs-de-poisson"],
  ["orange sanguine", "orange-sanguine"],
  ["orange-sanguine", "orange-sanguine"],
  ["pate a tartiner", "pate-a-tartiner"],
  ["pâte à tartiner", "pate-a-tartiner"],
  ["pate-a-tartiner", "pate-a-tartiner"],
  ["pates completes", "pates-completes"],
  ["pâtes complètes", "pates-completes"],
  ["pates-completes", "pates-completes"],
  ["pepite chocolat", "pepite-chocolat"],
  ["pepite-chocolat", "pepite-chocolat"],
  ["piment jalapeno", "piment-jalapeno"],
  ["piment-jalapeno", "piment-jalapeno"],
  ["pois mange tout", "pois-mange-tout"],
  ["pois mange-tout", "pois-mange-tout"],
  ["pois-mange-tout", "pois-mange-tout"],
  ["poudre d'oignon", "poudre-oignon"],
  ["puree de tomate", "puree-de-tomate"],
  ["purée de tomate", "puree-de-tomate"],
  ["puree-de-tomate", "puree-de-tomate"],
  ["risotto prepare", "risotto-prepare"],
  ["risotto-prepare", "risotto-prepare"],
  ["saké de cuisine", "sake-cuisine"],
  ["sauce carbonara", "sauce-carbonara"],
  ["sauce-carbonara", "sauce-carbonara"],
  ["semoule au lait", "semoule-au-lait"],
  ["semoule de maïs", "mais-semoule"],
  ["semoule-au-lait", "semoule-au-lait"],
  ["souris d agneau", "souris-d-agneau"],
  ["souris d'agneau", "souris-d-agneau"],
  ["souris-d-agneau", "souris-d-agneau"],
  ["travers de porc", "travers-de-porc"],
  ["travers-de-porc", "travers-de-porc"],
  ["veloute potiron", "veloute-potiron"],
  ["veloute-potiron", "veloute-potiron"],
  ["vinaigre de riz", "vinaigre-riz"],
  ["aile de poulet", "aile-de-poulet"],
  ["aile-de-poulet", "aile-de-poulet"],
  ["amande effilee", "amande-effilee"],
  ["amande effilée", "amande-effilee"],
  ["amande grillee", "amande-grillee"],
  ["amande grillée", "amande-grillee"],
  ["amande-effilee", "amande-effilee"],
  ["amande-grillee", "amande-grillee"],
  ["baie de sureau", "sureau"],
  ["barre cereales", "barre-cereales"],
  ["barre-cereales", "barre-cereales"],
  ["blanc de dinde", "blanc-de-dinde"],
  ["blanc-de-dinde", "blanc-de-dinde"],
  ["chocolat blanc", "chocolat-blanc"],
  ["chocolat chaud", "chocolat-chaud"],
  ["chocolat-blanc", "chocolat-blanc"],
  ["chocolat-chaud", "chocolat-chaud"],
  ["chou romanesco", "chou-romanesco"],
  ["chou-romanesco", "chou-romanesco"],
  ["cognac cuisine", "cognac-cuisine"],
  ["cognac-cuisine", "cognac-cuisine"],
  ["cottage cheese", "cottage-cheese"],
  ["cottage-cheese", "cottage-cheese"],
  ["creme anglaise", "creme-anglaise"],
  ["crème anglaise", "creme-anglaise"],
  ["creme fouettee", "creme-fouettee"],
  ["crème fouettée", "creme-fouettee"],
  ["creme-anglaise", "creme-anglaise"],
  ["creme-fouettee", "creme-fouettee"],
  ["crevette grise", "crevette-grise"],
  ["crevette-grise", "crevette-grise"],
  ["échine de porc", "echine"],
  ["edamame graine", "edamame-graine"],
  ["edamame-graine", "edamame-graine"],
  ["épeautre perlé", "ebly"],
  ["farine de maïs", "farine-mais"],
  ["fecule de mais", "fecule-de-mais"],
  ["fécule de maïs", "fecule-de-mais"],
  ["fecule-de-mais", "fecule-de-mais"],
  ["fenouil graine", "fenouil-graine"],
  ["fenouil-graine", "fenouil-graine"],
  ["filet de boeuf", "filet-de-boeuf"],
  ["filet-de-boeuf", "filet-de-boeuf"],
  ["fish and chips", "fish-and-chips"],
  ["fish-and-chips", "fish-and-chips"],
  ["galette de riz", "galette-de-riz"],
  ["galette-de-riz", "galette-de-riz"],
  ["gigot d'agneau", "gigot"],
  ["graine de chia", "graine-de-chia"],
  ["graine-de-chia", "graine-de-chia"],
  ["haricot beurre", "haricot-beurre"],
  ["haricot-beurre", "haricot-beurre"],
  ["huile arachide", "huile-arachide"],
  ["huile cameline", "huile-cameline"],
  ["huile d'avocat", "huile-avocat"],
  ["huile de colza", "huile-colza"],
  ["huile de palme", "huile-de-palme"],
  ["huile-arachide", "huile-arachide"],
  ["huile-cameline", "huile-cameline"],
  ["huile-de-palme", "huile-de-palme"],
  ["lait chocolaté", "lait-chocolat"],
  ["lait concentre", "lait-concentre"],
  ["lait concentré", "lait-concentre"],
  ["lait de brebis", "lait-de-brebis"],
  ["lait de chevre", "lait-de-chevre"],
  ["lait de chèvre", "lait-de-chevre"],
  ["lait en poudre", "lait-en-poudre"],
  ["lait-concentre", "lait-concentre"],
  ["lait-de-brebis", "lait-de-brebis"],
  ["lait-de-chevre", "lait-de-chevre"],
  ["lait-en-poudre", "lait-en-poudre"],
  ["langue de bœuf", "langue-de-boeuf"],
  ["menthe poivree", "menthe-poivree"],
  ["menthe poivrée", "menthe-poivree"],
  ["menthe-poivree", "menthe-poivree"],
  ["muffin anglais", "muffin-anglais"],
  ["muffin-anglais", "muffin-anglais"],
  ["noix du bresil", "noix-du-bresil"],
  ["noix du brésil", "noix-du-bresil"],
  ["noix-du-bresil", "noix-du-bresil"],
  ["oeuf de caille", "oeuf-de-caille"],
  ["oeuf-de-caille", "oeuf-de-caille"],
  ["oeufs de lompe", "oeufs-de-lompe"],
  ["oeufs-de-lompe", "oeufs-de-lompe"],
  ["oignon nouveau", "oignon-nouveau"],
  ["oignon-nouveau", "oignon-nouveau"],
  ["pain au levain", "pain-au-levain"],
  ["pain de seigle", "pain-de-seigle"],
  ["pain-au-levain", "pain-au-levain"],
  ["pain-de-seigle", "pain-de-seigle"],
  ["piment cayenne", "piment-cayenne"],
  ["piment-cayenne", "piment-cayenne"],
  ["poire williams", "poire-williams"],
  ["poire-williams", "poire-williams"],
  ["poitrine fumee", "poitrine-fumee"],
  ["poitrine fumée", "poitrine-fumee"],
  ["poitrine-fumee", "poitrine-fumee"],
  ["poivre sichuan", "poivre-sichuan"],
  ["poivre-sichuan", "poivre-sichuan"],
  ["poivron orange", "poivron-orange"],
  ["poivron-orange", "poivron-orange"],
  ["pomme de terre", "pomme-de-terre"],
  ["pomme-de-terre", "pomme-de-terre"],
  ["pousse de soja", "pousse-soja"],
  ["puree d amande", "puree-d-amande"],
  ["purée d'amande", "puree-d-amande"],
  ["puree-d-amande", "puree-d-amande"],
  ["quark allemand", "quark-allemand"],
  ["quark-allemand", "quark-allemand"],
  ["queue de boeuf", "queue-de-boeuf"],
  ["queue-de-boeuf", "queue-de-boeuf"],
  ["salade iceberg", "iceberg"],
  ["sauce barbecue", "sauce-bbq"],
  ["sauce d'huître", "sauce-huitre"],
  ["sauce teriyaki", "sauce-teriyaki"],
  ["sauce-teriyaki", "sauce-teriyaki"],
  ["sirop d'érable", "sirop-erable"],
  ["vinaigre cidre", "vinaigre-cidre"],
  ["vinaigre xeres", "vinaigre-xeres"],
  ["vinaigre-cidre", "vinaigre-cidre"],
  ["vinaigre-xeres", "vinaigre-xeres"],
  ["worcestershire", "sauce-worcestershire"],
  ["yaourt a boire", "yaourt-a-boire"],
  ["yaourt à boire", "yaourt-a-boire"],
  ["yaourt-a-boire", "yaourt-a-boire"],
  ["anchois huile", "anchois-huile"],
  ["anchois-huile", "anchois-huile"],
  ["arome vanille", "arome-vanille"],
  ["arôme vanille", "arome-vanille"],
  ["arome-vanille", "arome-vanille"],
  ["bouquet garni", "bouquet-garni"],
  ["bouquet-garni", "bouquet-garni"],
  ["bûche de noël", "buche"],
  ["cajou grillée", "noix-de-cajou-grillee"],
  ["chips de coco", "chips-de-coco"],
  ["chips-de-coco", "chips-de-coco"],
  ["chocolat lait", "chocolat-lait"],
  ["chocolat noir", "chocolat-noir"],
  ["chocolat-lait", "chocolat-lait"],
  ["chocolat-noir", "chocolat-noir"],
  ["conserve thon", "conserve-thon"],
  ["conserve-thon", "conserve-thon"],
  ["coulis fruits", "coulis-fruits"],
  ["coulis tomate", "coulis-tomate"],
  ["coulis-fruits", "coulis-fruits"],
  ["coulis-tomate", "coulis-tomate"],
  ["couscous plat", "couscous-plat"],
  ["couscous-plat", "couscous-plat"],
  ["creme de coco", "creme-de-coco"],
  ["crème de coco", "creme-de-coco"],
  ["creme epaisse", "creme-epaisse"],
  ["crème épaisse", "creme-epaisse"],
  ["creme fraiche", "creme"],
  ["crème fraîche", "creme"],
  ["creme liquide", "creme-liquide"],
  ["crème liquide", "creme-liquide"],
  ["creme-de-coco", "creme-de-coco"],
  ["creme-epaisse", "creme-epaisse"],
  ["creme-liquide", "creme-liquide"],
  ["cube bouillon", "cube-bouillon"],
  ["cube-bouillon", "cube-bouillon"],
  ["curcuma frais", "curcuma-frais"],
  ["curcuma-frais", "curcuma-frais"],
  ["epaule agneau", "epaule-agneau"],
  ["epaule-agneau", "epaule-agneau"],
  ["escalope veau", "escalope-veau"],
  ["escalope-veau", "escalope-veau"],
  ["farine de riz", "farine-riz"],
  ["farine seigle", "farine-seigle"],
  ["farine-seigle", "farine-seigle"],
  ["filet de bœuf", "filet-de-boeuf"],
  ["foie de morue", "foie-de-morue"],
  ["foie-de-morue", "foie-de-morue"],
  ["fromage blanc", "fromage-blanc"],
  ["fromage fondu", "kiri"],
  ["fromage frais", "fromage-frais"],
  ["fromage-blanc", "fromage-blanc"],
  ["fromage-frais", "fromage-frais"],
  ["grain de café", "cafe-grain"],
  ["graine de lin", "graine-de-lin"],
  ["graine-de-lin", "graine-de-lin"],
  ["graisse d oie", "graisse-d-oie"],
  ["graisse d'oie", "graisse-d-oie"],
  ["graisse-d-oie", "graisse-d-oie"],
  ["grand marnier", "grand-marnier"],
  ["grand-marnier", "grand-marnier"],
  ["haricot azuki", "azuki"],
  ["haricot blanc", "haricot-blanc"],
  ["haricot mungo", "mungo"],
  ["haricot rouge", "haricot-rouge"],
  ["haricot-blanc", "haricot-blanc"],
  ["haricot-rouge", "haricot-rouge"],
  ["huile d olive", "huile-olive"],
  ["huile d'olive", "huile-olive"],
  ["huile de coco", "huile-coco"],
  ["huile de noix", "huile-noix"],
  ["ile flottante", "ile-flottante"],
  ["île flottante", "ile-flottante"],
  ["ile-flottante", "ile-flottante"],
  ["jus de citron", "jus-de-citron"],
  ["jus de tomate", "jus-de-tomate"],
  ["jus-de-citron", "jus-de-citron"],
  ["jus-de-tomate", "jus-de-tomate"],
  ["kefir de lait", "kefir-de-lait"],
  ["kéfir de lait", "kefir-de-lait"],
  ["kefir-de-lait", "kefir-de-lait"],
  ["lait chocolat", "lait-chocolat"],
  ["lait d amande", "lait-d-amande"],
  ["lait d avoine", "lait-d-avoine"],
  ["lait d'amande", "lait-d-amande"],
  ["lait d'avoine", "lait-d-avoine"],
  ["lait fermente", "lait-fermente"],
  ["lait fermenté", "lait-fermente"],
  ["lait-chocolat", "lait-chocolat"],
  ["lait-d-amande", "lait-d-amande"],
  ["lait-d-avoine", "lait-d-avoine"],
  ["lait-fermente", "lait-fermente"],
  ["lasagnes plat", "lasagnes-plat"],
  ["lasagnes-plat", "lasagnes-plat"],
  ["noix de cajou", "noix-de-cajou"],
  ["noix de pecan", "noix-de-pecan"],
  ["noix de pécan", "noix-de-pecan"],
  ["noix-de-cajou", "noix-de-cajou"],
  ["noix-de-pecan", "noix-de-pecan"],
  ["nouilles soba", "nouilles-soba"],
  ["nouilles udon", "nouilles-udon"],
  ["nouilles-soba", "nouilles-soba"],
  ["nouilles-udon", "nouilles-udon"],
  ["œuf de caille", "oeuf-de-caille"],
  ["œufs de lompe", "oeufs-de-lompe"],
  ["oignon pickle", "oignon-pickle"],
  ["oignon-pickle", "oignon-pickle"],
  ["pain d epices", "pain-d-epices"],
  ["pain d'épices", "pain-d-epices"],
  ["pain-d-epices", "pain-d-epices"],
  ["pate d amande", "pate-d-amande"],
  ["pâte d'amande", "pate-d-amande"],
  ["pate de curry", "pate-de-curry"],
  ["pâte de curry", "pate-de-curry"],
  ["pate de fruit", "pate-de-fruit"],
  ["pâte de fruit", "pate-de-fruit"],
  ["pate-d-amande", "pate-d-amande"],
  ["pate-de-curry", "pate-de-curry"],
  ["pate-de-fruit", "pate-de-fruit"],
  ["pignon de pin", "pignon"],
  ["piment oiseau", "piment-oiseau"],
  ["piment padron", "piment-padron"],
  ["piment padrón", "piment-padron"],
  ["piment-oiseau", "piment-oiseau"],
  ["piment-padron", "piment-padron"],
  ["poivron corne", "poivron-corne"],
  ["poivron jaune", "poivron-jaune"],
  ["poivron-corne", "poivron-corne"],
  ["poivron-jaune", "poivron-jaune"],
  ["pont-l'évêque", "pont-leveque"],
  ["poudre oignon", "poudre-oignon"],
  ["poudre-oignon", "poudre-oignon"],
  ["poulet entier", "poulet-entier"],
  ["poulet-entier", "poulet-entier"],
  ["pousse bambou", "pousse-bambou"],
  ["pousse-bambou", "pousse-bambou"],
  ["queue de bœuf", "queue-de-boeuf"],
  ["ras el hanout", "ras-el-hanout"],
  ["ras-el-hanout", "ras-el-hanout"],
  ["ricotta salee", "ricotta-salee"],
  ["ricotta salée", "ricotta-salee"],
  ["ricotta-salee", "ricotta-salee"],
  ["saindoux bloc", "saindoux-bloc"],
  ["saindoux-bloc", "saindoux-bloc"],
  ["saint jacques", "saint-jacques"],
  ["saint-jacques", "saint-jacques"],
  ["sardine huile", "sardine-huile"],
  ["sardine-huile", "sardine-huile"],
  ["sauce tartare", "tartare"],
  ["saucisson sec", "saucisson-sec"],
  ["saucisson-sec", "saucisson-sec"],
  ["sirop d'agave", "sirop-agave"],
  ["stevia poudre", "stevia-poudre"],
  ["stevia-poudre", "stevia-poudre"],
  ["stracciatella", "stracciatella"],
  ["sucre complet", "cassonade-complete"],
  ["sucre vanille", "sucre-vanille"],
  ["sucre vanillé", "sucre-vanille"],
  ["sucre-vanille", "sucre-vanille"],
  ["thon en boite", "thon-en-boite"],
  ["thon en boîte", "thon-en-boite"],
  ["thon-en-boite", "thon-en-boite"],
  ["tomate ananas", "tomate-ananas"],
  ["tomate cerise", "tomate-cerise"],
  ["tomate sechee", "tomate-sechee"],
  ["tomate séchée", "tomate-sechee"],
  ["tomate-ananas", "tomate-ananas"],
  ["tomate-cerise", "tomate-cerise"],
  ["tomate-sechee", "tomate-sechee"],
  ["whey chocolat", "whey-chocolat"],
  ["whey-chocolat", "whey-chocolat"],
  ["ail des ours", "ail-des-ours"],
  ["ail-des-ours", "ail-des-ours"],
  ["algue wakame", "algue-wakame"],
  ["algue-wakame", "algue-wakame"],
  ["baie de goji", "goji"],
  ["basilic thai", "basilic-thai"],
  ["basilic thaï", "basilic-thai"],
  ["basilic-thai", "basilic-thai"],
  ["blanc d oeuf", "blanc-d-oeuf"],
  ["blanc-d-oeuf", "blanc-d-oeuf"],
  ["boudin blanc", "boudin-blanc"],
  ["boudin-blanc", "boudin-blanc"],
  ["brocoli rabe", "brocoli-rabe"],
  ["brocoli-rabe", "brocoli-rabe"],
  ["cacao beurre", "cacao-beurre"],
  ["cacao-beurre", "cacao-beurre"],
  ["chorizo doux", "chorizo-doux"],
  ["chorizo-doux", "chorizo-doux"],
  ["chou chinois", "chou-chinois"],
  ["chou-chinois", "chou-chinois"],
  ["cœur de bœuf", "coeur-de-boeuf-abats"],
  ["cote de porc", "cote-de-porc"],
  ["côte de porc", "cote-de-porc"],
  ["cote-de-porc", "cote-de-porc"],
  ["creme aigrie", "creme-aigrie"],
  ["creme brulee", "creme-brulee"],
  ["crème brûlée", "creme-brulee"],
  ["creme-aigrie", "creme-aigrie"],
  ["creme-brulee", "creme-brulee"],
  ["dorade grise", "dorade-grise"],
  ["dorade-grise", "dorade-grise"],
  ["figue sechee", "figue-sechee"],
  ["figue séchée", "figue-sechee"],
  ["figue-sechee", "figue-sechee"],
  ["filet mignon", "filet-mignon"],
  ["filet-mignon", "filet-mignon"],
  ["fleur de sel", "fleur-de-sel"],
  ["fleur-de-sel", "fleur-de-sel"],
  ["foie de veau", "foie-de-veau"],
  ["foie-de-veau", "foie-de-veau"],
  ["fond de veau", "fond-de-veau"],
  ["fond-de-veau", "fond-de-veau"],
  ["fromage rape", "fromage-rape"],
  ["fromage râpé", "fromage-rape"],
  ["fromage-rape", "fromage-rape"],
  ["garam masala", "garam-masala"],
  ["garam-masala", "garam-masala"],
  ["germe de ble", "germe-de-ble"],
  ["germe de blé", "germe-de-ble"],
  ["germe-de-ble", "germe-de-ble"],
  ["haricot coco", "haricot-coco"],
  ["haricot noir", "haricot-noir"],
  ["haricot vert", "haricot-vert"],
  ["haricot-coco", "haricot-coco"],
  ["haricot-noir", "haricot-noir"],
  ["haricot-vert", "haricot-vert"],
  ["huile avocat", "huile-avocat"],
  ["huile de lin", "huile-lin"],
  ["huile sesame", "huile-sesame"],
  ["huile-avocat", "huile-avocat"],
  ["huile-sesame", "huile-sesame"],
  ["jambon blanc", "jambon-blanc"],
  ["jambon-blanc", "jambon-blanc"],
  ["jaune d oeuf", "jaune-d-oeuf"],
  ["jaune-d-oeuf", "jaune-d-oeuf"],
  ["jus d orange", "jus-d-orange"],
  ["jus d'orange", "jus-d-orange"],
  ["jus de pomme", "jus-de-pomme"],
  ["jus-d-orange", "jus-d-orange"],
  ["jus-de-pomme", "jus-de-pomme"],
  ["kouign amann", "kouign-amann"],
  ["kouign-amann", "kouign-amann"],
  ["lait de coco", "lait-de-coco"],
  ["lait de soja", "lait-de-soja"],
  ["lait-de-coco", "lait-de-coco"],
  ["lait-de-soja", "lait-de-soja"],
  ["lentille puy", "lentille-puy"],
  ["lentille-puy", "lentille-puy"],
  ["mais semoule", "mais-semoule"],
  ["mais-semoule", "mais-semoule"],
  ["miel cremeux", "miel-cremeux"],
  ["miel crémeux", "miel-cremeux"],
  ["miel-cremeux", "miel-cremeux"],
  ["millefeuille", "millefeuille"],
  ["noix de coco", "noix-de-coco"],
  ["noix-de-coco", "noix-de-coco"],
  ["nouilles riz", "nouilles-riz"],
  ["nouilles-riz", "nouilles-riz"],
  ["oeuf de cane", "oeuf-de-cane"],
  ["oeuf-de-cane", "oeuf-de-cane"],
  ["oignon blanc", "oignon-blanc"],
  ["oignon jaune", "oignon-jaune"],
  ["oignon rouge", "oignon-rouge"],
  ["oignon-blanc", "oignon-blanc"],
  ["oignon-jaune", "oignon-jaune"],
  ["oignon-rouge", "oignon-rouge"],
  ["olive casher", "olive-casher"],
  ["olive-casher", "olive-casher"],
  ["pain brioche", "pain-brioche"],
  ["pain brioché", "pain-brioche"],
  ["pain complet", "pain-complet"],
  ["pain-brioche", "pain-brioche"],
  ["pain-complet", "pain-complet"],
  ["pamplemousse", "pamplemousse"],
  ["paprika fume", "paprika-fume"],
  ["paprika fumé", "paprika-fume"],
  ["paprika-fume", "paprika-fume"],
  ["patate douce", "patate-douce"],
  ["patate-douce", "patate-douce"],
  ["persil frise", "persil-frise"],
  ["persil frisé", "persil-frise"],
  ["persil-frise", "persil-frise"],
  ["petit suisse", "petit-suisse"],
  ["petit-suisse", "petit-suisse"],
  ["poivre blanc", "poivre-blanc"],
  ["poivre-blanc", "poivre-blanc"],
  ["poivron vert", "poivron-vert"],
  ["poivron-vert", "poivron-vert"],
  ["pomme golden", "pomme-golden"],
  ["pomme granny", "pomme-granny"],
  ["pomme-golden", "pomme-golden"],
  ["pomme-granny", "pomme-granny"],
  ["pont leveque", "pont-leveque"],
  ["pont-leveque", "pont-leveque"],
  ["poudre d'ail", "poudre-ail"],
  ["quinoa rouge", "quinoa-rouge"],
  ["quinoa-rouge", "quinoa-rouge"],
  ["raisin blanc", "raisin-blanc"],
  ["raisin-blanc", "raisin-blanc"],
  ["reine-claude", "prune-reine-claude"],
  ["rhum arrange", "rhum-arrange"],
  ["rhum arrangé", "rhum-arrange"],
  ["rhum-arrange", "rhum-arrange"],
  ["roti de porc", "roti-de-porc"],
  ["rôti de porc", "roti-de-porc"],
  ["roti-de-porc", "roti-de-porc"],
  ["saint honore", "saint-honore"],
  ["saint pierre", "saint-pierre"],
  ["saint-honore", "saint-honore"],
  ["saint-honoré", "saint-honore"],
  ["saint-pierre", "saint-pierre"],
  ["sainte maure", "sainte-maure"],
  ["sainte-maure", "sainte-maure"],
  ["sake cuisine", "sake-cuisine"],
  ["sake-cuisine", "sake-cuisine"],
  ["sauce huitre", "sauce-huitre"],
  ["sauce tomate", "sauce-tomate"],
  ["sauce-huitre", "sauce-huitre"],
  ["sauce-tomate", "sauce-tomate"],
  ["sirop erable", "sirop-erable"],
  ["sirop-erable", "sirop-erable"],
  ["son d avoine", "son-d-avoine"],
  ["son d'avoine", "son-d-avoine"],
  ["son-d-avoine", "son-d-avoine"],
  ["truite fumee", "truite-fumee"],
  ["truite fumée", "truite-fumee"],
  ["truite-fumee", "truite-fumee"],
  ["vinaigre riz", "vinaigre-riz"],
  ["vinaigre-riz", "vinaigre-riz"],
  ["wasabi frais", "wasabi-frais"],
  ["wasabi-frais", "wasabi-frais"],
  ["whey vanille", "whey-vanille"],
  ["whey-vanille", "whey-vanille"],
  ["yaourt glace", "yaourt-glace"],
  ["yaourt glacé", "yaourt-glace"],
  ["yaourt-glace", "yaourt-glace"],
  ["anis etoile", "anis-etoile"],
  ["anis étoilé", "anis-etoile"],
  ["anis-etoile", "anis-etoile"],
  ["beurre doux", "beurre-doux"],
  ["beurre sale", "beurre-sale"],
  ["beurre salé", "beurre-sale"],
  ["beurre-doux", "beurre-doux"],
  ["beurre-sale", "beurre-sale"],
  ["bicarbonate", "bicarbonate"],
  ["blanc d'œuf", "blanc-d-oeuf"],
  ["boudin noir", "boudin-noir"],
  ["boudin-noir", "boudin-noir"],
  ["bourguignon", "bourguignon"],
  ["carrot cake", "carrot-cake"],
  ["carrot-cake", "carrot-cake"],
  ["celeri rave", "celeri-rave"],
  ["celeri-rave", "celeri-rave"],
  ["céleri-rave", "celeri-rave"],
  ["chimichurri", "chimichurri"],
  ["cinq epices", "cinq-epices"],
  ["cinq épices", "cinq-epices"],
  ["cinq-epices", "cinq-epices"],
  ["citron vert", "citron-vert"],
  ["citron-vert", "citron-vert"],
  ["citronnelle", "citronnelle"],
  ["cordon bleu", "cordon-bleu"],
  ["cordon-bleu", "cordon-bleu"],
  ["coulommiers", "coulommiers"],
  ["crème aigre", "creme-aigrie"],
  ["eau de rose", "eau-de-rose"],
  ["eau gazeuse", "eau-gazeuse"],
  ["eau-de-rose", "eau-de-rose"],
  ["eau-gazeuse", "eau-gazeuse"],
  ["farine mais", "farine-mais"],
  ["farine-mais", "farine-mais"],
  ["foret noire", "foret-noire"],
  ["foret-noire", "foret-noire"],
  ["forêt-noire", "foret-noire"],
  ["hache boeuf", "hache-boeuf"],
  ["hache-boeuf", "hache-boeuf"],
  ["hareng fume", "hareng-fume"],
  ["hareng fumé", "hareng-fume"],
  ["hareng-fume", "hareng-fume"],
  ["haricot sec", "haricot-sec"],
  ["haricot-sec", "haricot-sec"],
  ["hollandaise", "hollandaise"],
  ["huile colza", "huile-colza"],
  ["huile olive", "huile-olive"],
  ["huile-colza", "huile-colza"],
  ["huile-olive", "huile-olive"],
  ["jaune d'œuf", "jaune-d-oeuf"],
  ["lait de riz", "lait-de-riz"],
  ["lait ecreme", "lait-ecreme"],
  ["lait écrémé", "lait-ecreme"],
  ["lait entier", "lait-entier"],
  ["lait-de-riz", "lait-de-riz"],
  ["lait-ecreme", "lait-ecreme"],
  ["lait-entier", "lait-entier"],
  ["langoustine", "langoustine"],
  ["loup de mer", "loup-de-mer"],
  ["loup-de-mer", "loup-de-mer"],
  ["œuf de cane", "oeuf-de-cane"],
  ["olive noire", "olive-noire"],
  ["olive verte", "olive-verte"],
  ["olive-noire", "olive-noire"],
  ["olive-verte", "olive-verte"],
  ["os a moelle", "os-a-moelle"],
  ["os à moelle", "os-a-moelle"],
  ["os-a-moelle", "os-a-moelle"],
  ["pain de mie", "pain-de-mie"],
  ["pain-de-mie", "pain-de-mie"],
  ["panna cotta", "panna-cotta"],
  ["panna-cotta", "panna-cotta"],
  ["paris brest", "paris-brest"],
  ["paris-brest", "paris-brest"],
  ["pesto rosso", "pesto-rosso"],
  ["pesto-rosso", "pesto-rosso"],
  ["piment doux", "piment-doux"],
  ["piment-doux", "piment-doux"],
  ["pois chiche", "pois-chiche"],
  ["pois-chiche", "pois-chiche"],
  ["poivre long", "poivre-long"],
  ["poivre vert", "poivre-vert"],
  ["poivre-long", "poivre-long"],
  ["poivre-vert", "poivre-vert"],
  ["pousse soja", "pousse-soja"],
  ["pousse-soja", "pousse-soja"],
  ["profiterole", "profiterole"],
  ["ratatouille", "ratatouille"],
  ["riz arborio", "risotto"],
  ["riz au lait", "riz-au-lait"],
  ["riz basmati", "riz-basmati"],
  ["riz complet", "riz-complet"],
  ["riz sauvage", "riz-sauvage"],
  ["riz-au-lait", "riz-au-lait"],
  ["riz-basmati", "riz-basmati"],
  ["riz-complet", "riz-complet"],
  ["riz-sauvage", "riz-sauvage"],
  ["sauce chili", "sauce-chili"],
  ["sauce-chili", "sauce-chili"],
  ["saumon fume", "saumon-fume"],
  ["saumon fumé", "saumon-fume"],
  ["saumon-fume", "saumon-fume"],
  ["sesame noir", "sesame-noir"],
  ["sésame noir", "sesame-noir"],
  ["sesame-noir", "sesame-noir"],
  ["sirop agave", "sirop-agave"],
  ["sirop-agave", "sirop-agave"],
  ["skyr nature", "skyr-nature"],
  ["skyr-nature", "skyr-nature"],
  ["steak hache", "steak-hache"],
  ["steak haché", "steak-hache"],
  ["steak-hache", "steak-hache"],
  ["sucre glace", "sucre-glace"],
  ["sucre-glace", "sucre-glace"],
  ["tagliatelle", "tagliatelle"],
  ["tarte salee", "tarte-salee"],
  ["tarte salée", "tarte-salee"],
  ["tarte tatin", "tarte-tatin"],
  ["tarte-salee", "tarte-salee"],
  ["tarte-tatin", "tarte-tatin"],
  ["tofu soyeux", "tofu-soyeux"],
  ["tofu-soyeux", "tofu-soyeux"],
  ["topinambour", "topinambour"],
  ["yaourt grec", "yaourt-grec"],
  ["yaourt-grec", "yaourt-grec"],
  ["algue nori", "algue-nori"],
  ["algue-nori", "algue-nori"],
  ["arrow root", "arrow-root"],
  ["arrow-root", "arrow-root"],
  ["blanquette", "blanquette"],
  ["bœuf haché", "hache-boeuf"],
  ["bol d'udon", "udon-bol"],
  ["cafe grain", "cafe-grain"],
  ["cafe-grain", "cafe-grain"],
  ["canneberge", "canneberge"],
  ["champignon", "champignon"],
  ["cheesecake", "cheesecake"],
  ["chou fleur", "chou-fleur"],
  ["chou rouge", "chou-rouge"],
  ["chou-fleur", "chou-fleur"],
  ["chou-rouge", "chou-rouge"],
  ["choucroute", "choucroute"],
  ["chouquette", "chouquette"],
  ["ciboulette", "ciboulette"],
  ["clementine", "clementine"],
  ["clémentine", "clementine"],
  ["curry plat", "curry-plat"],
  ["curry-plat", "curry-plat"],
  ["édulcorant", "aspartame"],
  ["farine riz", "farine-riz"],
  ["farine-riz", "farine-riz"],
  ["faux filet", "faux-filet"],
  ["faux-filet", "faux-filet"],
  ["fettuccine", "fettuccine"],
  ["ginger ale", "ginger-ale"],
  ["ginger-ale", "ginger-ale"],
  ["gorgonzola", "gorgonzola"],
  ["hache porc", "hache-porc"],
  ["hache-porc", "hache-porc"],
  ["huile coco", "huile-coco"],
  ["huile noix", "huile-noix"],
  ["huile-coco", "huile-coco"],
  ["huile-noix", "huile-noix"],
  ["jambon cru", "jambon-cru"],
  ["jambon-cru", "jambon-cru"],
  ["jambonneau", "jambonneau"],
  ["kiwi jaune", "kiwi-jaune"],
  ["kiwi-jaune", "kiwi-jaune"],
  ["lait ribot", "lait-ribot"],
  ["lait-ribot", "lait-ribot"],
  ["lieu jaune", "lieu-jaune"],
  ["lieu-jaune", "lieu-jaune"],
  ["mangoustan", "mangoustan"],
  ["marjolaine", "marjolaine"],
  ["mascarpone", "mascarpone"],
  ["mayonnaise", "mayonnaise"],
  ["minestrone", "minestrone"],
  ["mortadelle", "mortadelle"],
  ["mozzarella", "mozzarella"],
  ["oeuf blanc", "oeuf-blanc"],
  ["oeuf-blanc", "oeuf-blanc"],
  ["petit pois", "petit-pois"],
  ["petit-pois", "petit-pois"],
  ["pois casse", "pois-casse"],
  ["pois cassé", "pois-casse"],
  ["pois-casse", "pois-casse"],
  ["porc haché", "hache-porc"],
  ["potimarron", "potimarron"],
  ["poudre ail", "poudre-ail"],
  ["poudre-ail", "poudre-ail"],
  ["prosciutto", "prosciutto"],
  ["radis noir", "radis-noir"],
  ["radis-noir", "radis-noir"],
  ["raisin sec", "raisin-sec"],
  ["raisin-sec", "raisin-sec"],
  ["riz gluant", "riz-gluant"],
  ["riz-gluant", "riz-gluant"],
  ["rocamadour", "rocamadour"],
  ["sauce soja", "sauce-soja"],
  ["sauce-soja", "sauce-soja"],
  ["shortening", "shortening"],
  ["son de ble", "son-de-ble"],
  ["son de blé", "son-de-ble"],
  ["son-de-ble", "son-de-ble"],
  ["sucre roux", "sucre-roux"],
  ["sucre-roux", "sucre-roux"],
  ["thon blanc", "thon-blanc"],
  ["thon-blanc", "thon-blanc"],
  ["tortellini", "tortellini"],
  ["vermicelle", "vermicelle"],
  ["abondance", "abondance"],
  ["agar agar", "agar-agar"],
  ["agar-agar", "agar-agar"],
  ["anchoiade", "anchoiade"],
  ["anchoïade", "anchoiade"],
  ["andouille", "andouille"],
  ["argousier", "argousier"],
  ["artichaut", "artichaut"],
  ["aspartame", "aspartame"],
  ["aubergine", "aubergine"],
  ["bearnaise", "bearnaise"],
  ["béarnaise", "bearnaise"],
  ["bergamote", "bergamote"],
  ["betterave", "betterave"],
  ["bigorneau", "bigorneau"],
  ["butternut", "butternut"],
  ["cabillaud", "cabillaud"],
  ["cacahuete", "cacahuete"],
  ["cacahuète", "cacahuete"],
  ["camembert", "camembert"],
  ["carambole", "carambole"],
  ["cardamome", "cardamome"],
  ["cassonade", "cassonade"],
  ["champagne", "champagne"],
  ["chapelure", "chapelure"],
  ["chataigne", "chataigne"],
  ["châtaigne", "chataigne"],
  ["chevreuil", "chevreuil"],
  ["chipolata", "chipolata"],
  ["chou kale", "chou-kale"],
  ["chou rave", "chou-rave"],
  ["chou-kale", "chou-kale"],
  ["chou-rave", "chou-rave"],
  ["clafoutis", "clafoutis"],
  ["cointreau", "cointreau"],
  ["concombre", "concombre"],
  ["confiture", "confiture"],
  ["coriandre", "coriandre"],
  ["cornichon", "cornichon"],
  ["courgette", "courgette"],
  ["croissant", "croissant"],
  ["entrecote", "entrecote"],
  ["entrecôte", "entrecote"],
  ["faisselle", "faisselle"],
  ["financier", "financier"],
  ["flageolet", "haricot-flageolet"],
  ["foie gras", "foie-gras"],
  ["foie-gras", "foie-gras"],
  ["framboise", "framboise"],
  ["gingembre", "gingembre"],
  ["groseille", "groseille"],
  ["guacamole", "guacamole"],
  ["guanciale", "guanciale"],
  ["huile lin", "huile-lin"],
  ["huile-lin", "huile-lin"],
  ["jackfruit", "jackfruit"],
  ["langouste", "langouste"],
  ["lieu noir", "lieu"],
  ["madeleine", "madeleine"],
  ["mais doux", "mais-doux"],
  ["maïs doux", "mais-doux"],
  ["mais-doux", "mais-doux"],
  ["mandarine", "mandarine"],
  ["maquereau", "maquereau"],
  ["margarine", "margarine"],
  ["marmelade", "marmelade"],
  ["maroilles", "maroilles"],
  ["massepain", "marzipan"],
  ["mimolette", "mimolette"],
  ["mont d or", "mont-d-or"],
  ["mont d'or", "mont-d-or"],
  ["mont-d-or", "mont-d-or"],
  ["muscovado", "muscovado"],
  ["nectarine", "nectarine"],
  ["œuf blanc", "oeuf-blanc"],
  ["pain pita", "pita"],
  ["pangasius", "pangasius"],
  ["ramboutan", "ramboutan"],
  ["reblochon", "reblochon"],
  ["rillettes", "rillettes"],
  ["riz rouge", "riz-rouge"],
  ["riz-rouge", "riz-rouge"],
  ["roquefort", "roquefort"],
  ["salicorne", "salicorne"],
  ["sarriette", "sarriette"],
  ["sauce bbq", "sauce-bbq"],
  ["sauce-bbq", "sauce-bbq"],
  ["saucisson", "saucisson"],
  ["shirataki", "shirataki"],
  ["spaghetti", "spaghetti"],
  ["speculoos", "speculoos"],
  ["spiruline", "spiruline"],
  ["thé glacé", "ice-tea"],
  ["tofu fume", "tofu-fume"],
  ["tofu fumé", "tofu-fume"],
  ["tofu-fume", "tofu-fume"],
  ["vergeoise", "vergeoise"],
  ["vin blanc", "vin-blanc"],
  ["vin-blanc", "vin-blanc"],
  ["absinthe", "absinthe"],
  ["ail noir", "ail-noir"],
  ["ail-noir", "ail-noir"],
  ["amarante", "amarante"],
  ["amaretto", "amaretto"],
  ["anguille", "anguille"],
  ["armagnac", "armagnac"],
  ["babeurre", "babeurre"],
  ["baguette", "baguette"],
  ["baudroie", "baudroie"],
  ["beaufort", "beaufort"],
  ["biscotte", "biscotte"],
  ["bouillon", "bouillon"],
  ["boulette", "boulette"],
  ["boulgour", "boulgour"],
  ["brandade", "brandade"],
  ["bresaola", "bresaola"],
  ["calvados", "calvados"],
  ["cannelle", "cannelle"],
  ["céréales", "cereales-petit-dejeuner"],
  ["cerfeuil", "cerfeuil"],
  ["chicoree", "chicoree"],
  ["chicorée", "chicoree"],
  ["chocolat", "chocolat"],
  ["ciabatta", "ciabatta"],
  ["colorant", "colorant"],
  ["compotee", "compotee"],
  ["compotée", "compotee"],
  ["couscous", "couscous"],
  ["crevette", "crevette"],
  ["echalote", "echalote"],
  ["échalote", "echalote"],
  ["emmental", "emmental"],
  ["empanada", "empanada"],
  ["encornet", "encornet"],
  ["epeautre", "epeautre"],
  ["épeautre", "epeautre"],
  ["epoisses", "epoisses"],
  ["époisses", "epoisses"],
  ["escargot", "escargot"],
  ["estragon", "estragon"],
  ["farfalle", "farfalle"],
  ["fenugrec", "fenugrec"],
  ["focaccia", "focaccia"],
  ["gaspacho", "gazpacho"],
  ["gazpacho", "gazpacho"],
  ["gelatine", "gelatine"],
  ["gélatine", "gelatine"],
  ["gomashio", "gomashio"],
  ["halloumi", "halloumi"],
  ["infusion", "infusion"],
  ["jacquier", "jackfruit"],
  ["jalapeño", "piment-jalapeno"],
  ["kombucha", "kombucha"],
  ["laguiole", "laguiole"],
  ["lasagnes", "lasagnes-plat"],
  ["lentille", "lentille"],
  ["limonade", "limonade"],
  ["linguine", "linguine"],
  ["macaroni", "macaroni"],
  ["marzipan", "marzipan"],
  ["meringue", "meringue"],
  ["moutarde", "moutarde"],
  ["myrtille", "myrtille"],
  ["noisette", "noisette"],
  ["nouilles", "nouilles"],
  ["nuoc mam", "nuoc-mam"],
  ["nuoc-mam", "nuoc-mam"],
  ["nuoc-mâm", "nuoc-mam"],
  ["pak choi", "pak-choi"],
  ["pak-choi", "pak-choi"],
  ["pak-choï", "pak-choi"],
  ["palourde", "palourde"],
  ["pancetta", "pancetta"],
  ["parmesan", "parmesan"],
  ["pasteque", "pasteque"],
  ["pastèque", "pasteque"],
  ["patisson", "patisson"],
  ["pâtisson", "patisson"],
  ["pecorino", "pecorino"],
  ["physalis", "physalis"],
  ["piperade", "piperade"],
  ["pipérade", "piperade"],
  ["pistache", "pistache"],
  ["pleurote", "pleurote"],
  ["porridge", "porridge"],
  ["pourpier", "pourpier"],
  ["psyllium", "psyllium"],
  ["raclette", "raclette"],
  ["rhubarbe", "rhubarbe"],
  ["riz noir", "riz-noir"],
  ["riz thai", "riz-thai"],
  ["riz thaï", "riz-thai"],
  ["riz-noir", "riz-noir"],
  ["riz-thai", "riz-thai"],
  ["roquette", "roquette"],
  ["rumsteck", "rumsteck"],
  ["rutabaga", "rutabaga"],
  ["saindoux", "saindoux"],
  ["salsifis", "salsifis"],
  ["sanglier", "sanglier"],
  ["sarrasin", "sarrasin"],
  ["saucisse", "saucisse"],
  ["sel rose", "sel-rose"],
  ["sel-rose", "sel-rose"],
  ["shiitake", "shiitake"],
  ["smoothie", "smoothie"],
  ["sriracha", "sriracha"],
  ["tapenade", "tapenade"],
  ["the noir", "the-noir"],
  ["thé noir", "the-noir"],
  ["the vert", "the-vert"],
  ["thé vert", "the-vert"],
  ["the-noir", "the-noir"],
  ["the-vert", "the-vert"],
  ["tiramisu", "tiramisu"],
  ["tortilla", "tortilla"],
  ["tourteau", "tourteau"],
  ["tzatziki", "tzatziki"],
  ["udon bol", "udon-bol"],
  ["udon-bol", "udon-bol"],
  ["vacherin", "vacherin"],
  ["valencay", "valencay"],
  ["valençay", "valencay"],
  ["verveine", "verveine"],
  ["vin rose", "vin-rose"],
  ["vin rosé", "vin-rose"],
  ["vin-rose", "vin-rose"],
  ["vinaigre", "vinaigre"],
  ["abricot", "abricot"],
  ["airelle", "airelle"],
  ["anchois", "anchois"],
  ["asperge", "asperge"],
  ["babybel", "babybel"],
  ["basilic", "basilic"],
  ["bavette", "bavette"],
  ["brioche", "brioche"],
  ["brochet", "brochet"],
  ["brocoli", "brocoli"],
  ["brownie", "brownie"],
  ["burrata", "burrata"],
  ["calamar", "calamar"],
  ["cannele", "cannele"],
  ["cannelé", "cannele"],
  ["caramel", "caramel"],
  ["carotte", "carotte"],
  ["cheddar", "cheddar"],
  ["chorizo", "chorizo"],
  ["chutney", "chutney"],
  ["ciboule", "ciboule"],
  ["compote", "compote"],
  ["cracker", "cracker"],
  ["cresson", "cresson"],
  ["crottin", "crottin"],
  ["crouton", "crouton"],
  ["croûton", "crouton"],
  ["curcuma", "curcuma"],
  ["daurade", "daurade"],
  ["dim sum", "dim-sum"],
  ["dim-sum", "dim-sum"],
  ["edamame", "edamame"],
  ["eglefin", "eglefin"],
  ["églefin", "eglefin"],
  ["epinard", "epinard"],
  ["épinard", "epinard"],
  ["espadon", "espadon"],
  ["etrille", "etrille"],
  ["étrille", "etrille"],
  ["falafel", "falafel"],
  ["fenouil", "fenouil"],
  ["fromage", "fromage"],
  ["fusilli", "fusilli"],
  ["galanga", "galanga"],
  ["ganache", "ganache"],
  ["girolle", "girolle"],
  ["gnocchi", "gnocchi"],
  ["gomasio", "gomasio"],
  ["granite", "granite"],
  ["granité", "granite"],
  ["granola", "granola"],
  ["grenade", "grenade"],
  ["griotte", "griotte"],
  ["grondin", "grondin"],
  ["gruyere", "gruyere"],
  ["gruyère", "gruyere"],
  ["harissa", "harissa"],
  ["hot dog", "hot-dog"],
  ["hot-dog", "hot-dog"],
  ["houmous", "hummus"],
  ["ice tea", "ice-tea"],
  ["ice-tea", "ice-tea"],
  ["iceberg", "iceberg"],
  ["ketchup", "ketchup"],
  ["kumquat", "kumquat"],
  ["lasagne", "lasagne"],
  ["laurier", "laurier"],
  ["limande", "limande"],
  ["livarot", "livarot"],
  ["longane", "longane"],
  ["macaron", "macaron"],
  ["merguez", "merguez"],
  ["mogette", "mogette"],
  ["morille", "morille"],
  ["munster", "munster"],
  ["muscade", "muscade"],
  ["nigelle", "nigelle"],
  ["oseille", "oseille"],
  ["paleron", "paleron"],
  ["pancake", "pancake"],
  ["paprika", "paprika"],
  ["passata", "passata"],
  ["pavlova", "pavlova"],
  ["pectine", "pectine"],
  ["pintade", "pintade"],
  ["poireau", "poireau"],
  ["poivron", "poivron"],
  ["polenta", "polenta"],
  ["potiron", "potiron"],
  ["pruneau", "pruneau"],
  ["raifort", "raifort"],
  ["ravioli", "ravioli"],
  ["ricotta", "ricotta"],
  ["risotto", "risotto-prepare"],
  ["romarin", "romarin"],
  ["sardine", "sardine"],
  ["sel fin", "sel-fin"],
  ["sel-fin", "sel-fin"],
  ["semoule", "semoule"],
  ["stilton", "stilton"],
  ["tabasco", "tabasco"],
  ["tamarin", "tamarin"],
  ["tapioca", "tapioca"],
  ["tarbais", "tarbais"],
  ["tartare", "tartare"],
  ["tequila", "tequila"],
  ["terrine", "terrine"],
  ["tilapia", "tilapia"],
  ["vanille", "vanille"],
  ["veloute", "veloute"],
  ["velouté", "veloute"],
  ["agneau", "agneau"],
  ["aligot", "aligot"],
  ["amande", "amande"],
  ["amidon", "amidon"],
  ["ananas", "ananas"],
  ["avocat", "avocat"],
  ["avoine", "avoine"],
  ["banane", "banane"],
  ["barbue", "barbue"],
  ["beurre", "beurre"],
  ["blette", "blette"],
  ["bonite", "bonite"],
  ["caille", "caille"],
  ["canard", "canard"],
  ["cantal", "cantal"],
  ["cardon", "cardon"],
  ["cassis", "cassis"],
  ["caviar", "caviar"],
  ["celeri", "celeri"],
  ["céleri", "celeri"],
  ["cerise", "cerise"],
  ["chevre", "chevre"],
  ["chèvre", "chevre"],
  ["citron", "citron"],
  ["cognac", "cognac-cuisine"],
  ["congre", "congre"],
  ["cookie", "cookie"],
  ["courge", "potiron"],
  ["daikon", "daikon"],
  ["durian", "durian"],
  ["echine", "echine"],
  ["eclair", "eclair"],
  ["éclair", "eclair"],
  ["endive", "endive"],
  ["farine", "farine"],
  ["fletan", "fletan"],
  ["flétan", "fletan"],
  ["fondue", "fondue"],
  ["fraise", "fraise"],
  ["frites", "frites"],
  ["gambas", "gambas"],
  ["gaufre", "gaufre"],
  ["goyave", "goyave"],
  ["hareng", "hareng"],
  ["homard", "homard"],
  ["huitre", "huitre"],
  ["huître", "huitre"],
  ["hummus", "hummus"],
  ["igname", "igname"],
  ["jambon", "jambon"],
  ["jarret", "jarret"],
  ["jujube", "jujube"],
  ["kimchi", "kimchi"],
  ["kirsch", "kirsch"],
  ["konjac", "konjac"],
  ["labneh", "labneh"],
  ["laitue", "laitue"],
  ["lardon", "lardon"],
  ["levure", "levure"],
  ["litchi", "litchi"],
  ["magret", "magret"],
  ["mangue", "mangue"],
  ["manioc", "manioc"],
  ["marron", "marron"],
  ["menthe", "menthe"],
  ["merlan", "merlan"],
  ["millet", "millet"],
  ["muesli", "muesli"],
  ["muffin", "muffin"],
  ["nougat", "nougat"],
  ["nugget", "nugget"],
  ["oignon", "oignon"],
  ["onglet", "onglet"],
  ["orange", "orange"],
  ["origan", "origan"],
  ["oursin", "oursin"],
  ["paella", "paella"],
  ["panais", "panais"],
  ["paneer", "paneer"],
  ["papaye", "papaye"],
  ["pastis", "pastis"],
  ["perche", "perche"],
  ["persil", "persil"],
  ["pickle", "pickle"],
  ["pignon", "pignon"],
  ["piment", "piment"],
  ["poivre", "poivre"],
  ["pomelo", "pomelo"],
  ["potage", "potage"],
  ["poulet", "poulet"],
  ["poulpe", "poulpe"],
  ["quiche", "quiche"],
  ["quinoa", "quinoa"],
  ["raisin", "raisin"],
  ["rognon", "rognon"],
  ["rosbif", "rosbif"],
  ["rouget", "rouget"],
  ["sables", "sables"],
  ["safran", "safran"],
  ["salade", "salade"],
  ["salami", "salami"],
  ["salers", "salers"],
  ["samosa", "samosa"],
  ["sandre", "sandre"],
  ["saumon", "saumon"],
  ["seiche", "seiche"],
  ["seitan", "seitan"],
  ["sorbet", "sorbet"],
  ["stevia", "stevia"],
  ["stévia", "stevia"],
  ["sureau", "sureau"],
  ["surimi", "surimi"],
  ["tahini", "tahini"],
  ["tajine", "tajine"],
  ["tarama", "tarama"],
  ["tempeh", "tempeh"],
  ["tomate", "tomate"],
  ["tourte", "tourte"],
  ["truffe", "truffe"],
  ["truite", "truite"],
  ["turbot", "turbot"],
  ["wakame", "algue-wakame"],
  ["wasabi", "wasabi"],
  ["whisky", "whisky"],
  ["yaourt", "yaourt"],
  ["zaatar", "zaatar"],
  ["aioli", "aioli"],
  ["aïoli", "aioli"],
  ["aneth", "aneth"],
  ["azuki", "azuki"],
  ["bacon", "bacon"],
  ["bagel", "bagel"],
  ["biere", "biere"],
  ["bière", "biere"],
  ["blini", "blini"],
  ["boeuf", "boeuf"],
  ["buche", "buche"],
  ["bulot", "bulot"],
  ["cacao", "cacao"],
  ["capre", "capre"],
  ["câpre", "capre"],
  ["carpe", "carpe"],
  ["chili", "chili"],
  ["chips", "chips"],
  ["choux", "choux"],
  ["cidre", "cidre"],
  ["coing", "coing"],
  ["colin", "colin"],
  ["comte", "comte"],
  ["comté", "comte"],
  ["coppa", "coppa"],
  ["coque", "coque"],
  ["crabe", "crabe"],
  ["creme", "creme"],
  ["crepe", "crepe"],
  ["crêpe", "crepe"],
  ["cumin", "cumin"],
  ["curry", "curry-plat"],
  ["dashi", "dashi"],
  ["datte", "datte"],
  ["dinde", "dinde"],
  ["donut", "donut"],
  ["epice", "epice"],
  ["figue", "figue"],
  ["gelee", "gelee"],
  ["gelée", "gelee"],
  ["gigot", "gigot"],
  ["glace", "glace"],
  ["gombo", "gombo"],
  ["gouda", "gouda"],
  ["gyoza", "gyoza"],
  ["hampe", "hampe"],
  ["huile", "huile"],
  ["kasha", "kasha"],
  ["kefir", "kefir"],
  ["kéfir", "kefir"],
  ["kefta", "kefta"],
  ["knack", "knack"],
  ["lapin", "lapin"],
  ["lotte", "lotte"],
  ["lupin", "lupin"],
  ["mache", "mache"],
  ["mâche", "mache"],
  ["melon", "melon"],
  ["merlu", "merlu"],
  ["mirin", "mirin"],
  ["moule", "moule"],
  ["mungo", "mungo"],
  ["navet", "navet"],
  ["olive", "olive"],
  ["opera", "opera"],
  ["opéra", "opera"],
  ["palme", "palme"],
  ["panko", "panko"],
  ["pates", "pates"],
  ["pâtes", "pates"],
  ["pavot", "pavot"],
  ["peche", "peche"],
  ["pêche", "peche"],
  ["penne", "penne"],
  ["pesto", "pesto"],
  ["pizza", "pizza"],
  ["poire", "poire"],
  ["pomme", "pomme"],
  ["porto", "porto"],
  ["prune", "prune"],
  ["puree", "puree"],
  ["purée", "puree"],
  ["quark", "quark"],
  ["radis", "radis"],
  ["raita", "raita"],
  ["ramen", "ramen"],
  ["sablé", "sables"],
  ["salsa", "salsa"],
  ["sauge", "sauge"],
  ["sirop", "sirop"],
  ["soupe", "soupe"],
  ["speck", "speck"],
  ["sprat", "sprat"],
  ["steak", "steak"],
  ["sucre", "sucre"],
  ["sumac", "sumac"],
  ["tarte", "tarte"],
  ["tomme", "tomme"],
  ["tonic", "tonic"],
  ["tripe", "tripe"],
  ["vodka", "vodka"],
  ["acai", "acai"],
  ["açaí", "acai"],
  ["agar", "agar"],
  ["anis", "anis"],
  ["bleu", "bleu"],
  ["bœuf", "boeuf"],
  ["brie", "brie"],
  ["cafe", "cafe"],
  ["café", "cafe"],
  ["cepe", "cepe"],
  ["cèpe", "cepe"],
  ["cerf", "cerf"],
  ["chou", "chou"],
  ["cola", "cola"],
  ["dahl", "dahl"],
  ["ebly", "ebly"],
  ["edam", "edam"],
  ["feta", "feta"],
  ["feve", "feve"],
  ["fève", "feve"],
  ["flan", "flan"],
  ["ghee", "ghee"],
  ["gite", "gite"],
  ["gîte", "gite"],
  ["goji", "goji"],
  ["kaki", "kaki"],
  ["kiri", "kiri"],
  ["kiwi", "kiwi"],
  ["lait", "lait"],
  ["lard", "lard"],
  ["lieu", "lieu"],
  ["mais", "mais"],
  ["maïs", "mais"],
  ["malt", "malt"],
  ["miel", "miel"],
  ["miso", "miso"],
  ["mure", "mure"],
  ["mûre", "mure"],
  ["naan", "naan"],
  ["noix", "noix"],
  ["nori", "algue-nori"],
  ["oeuf", "oeuf"],
  ["œufs", "oeuf"],
  ["orge", "orge"],
  ["orzo", "orzo"],
  ["pain", "pain"],
  ["pate", "pate"],
  ["pâté", "pate"],
  ["pita", "pita"],
  ["porc", "porc"],
  ["raie", "raie"],
  ["rhum", "rhum"],
  ["skyr", "skyr"],
  ["soja", "soja"],
  ["sole", "sole"],
  ["suif", "suif"],
  ["taro", "taro"],
  ["teff", "teff"],
  ["thon", "thon"],
  ["thym", "thym"],
  ["tofu", "tofu"],
  ["veau", "veau"],
  ["whey", "whey"],
  ["wrap", "wrap"],
  ["yuzu", "yuzu"],
  ["ail", "ail"],
  ["bao", "bao"],
  ["bar", "bar"],
  ["eau", "eau"],
  ["gin", "gin"],
  ["nem", "nem"],
  ["œuf", "oeuf"],
  ["oie", "oie"],
  ["pho", "pho"],
  ["phở", "pho"],
  ["riz", "riz"],
  ["sel", "sel"],
  ["the", "the"],
  ["thé", "the"],
  ["vin", "vin"],
];
