export const DEFAULT_TAGS = [
  { slug: 'viande', label: 'Viande' },
  { slug: 'poisson', label: 'Poisson' },
  { slug: 'fruits-de-mer', label: 'Fruits de mer' },
  { slug: 'vegetarien', label: 'Végétarien' },
  { slug: 'vegan', label: 'Vegan' },
  { slug: 'salade', label: 'Salade' },
  { slug: 'soupe', label: 'Soupe' },
  { slug: 'pates', label: 'Pâtes' },
  { slug: 'riz', label: 'Riz' },
  { slug: 'burger', label: 'Burger' },
  { slug: 'pizza', label: 'Pizza' },
  { slug: 'fast-food', label: 'Fast-food' },
  { slug: 'healthy', label: 'Healthy' },
  { slug: 'proteine', label: 'Protéiné' },
  { slug: 'dessert', label: 'Dessert' },
  { slug: 'patisserie', label: 'Pâtisserie' },
  { slug: 'petit-dejeuner', label: 'Petit-déjeuner' },
  { slug: 'gouter', label: 'Goûter' },
  { slug: 'aperitif', label: 'Apéritif' },
  { slug: 'plat-principal', label: 'Plat principal' },
  { slug: 'accompagnement', label: 'Accompagnement' },
  { slug: 'sauce', label: 'Sauce' },
  { slug: 'autre', label: 'Autre' },
] as const;

export const DEFAULT_EQUIPMENT = [
  { slug: 'four', label: 'Four' },
  { slug: 'micro-ondes', label: 'Micro-ondes' },
  { slug: 'air-fryer', label: 'Air fryer' },
  { slug: 'plaques', label: 'Plaques' },
  { slug: 'poele', label: 'Poêle' },
  { slug: 'casserole', label: 'Casserole' },
  { slug: 'wok', label: 'Wok' },
  { slug: 'blender', label: 'Blender' },
  { slug: 'mixeur-plongeant', label: 'Mixeur plongeant' },
  { slug: 'robot-patissier', label: 'Robot pâtissier' },
  { slug: 'robot-multifonction', label: 'Robot multifonction' },
  { slug: 'batteur', label: 'Batteur' },
  { slug: 'grille-pain', label: 'Grille-pain' },
  { slug: 'bouilloire', label: 'Bouilloire' },
  { slug: 'autocuiseur', label: 'Autocuiseur' },
  { slug: 'cocotte', label: 'Cocotte' },
  { slug: 'barbecue', label: 'Barbecue' },
  { slug: 'plancha', label: 'Plancha' },
  { slug: 'balance', label: 'Balance' },
  { slug: 'verre-doseur', label: 'Verre doseur' },
  { slug: 'saladier', label: 'Saladier' },
  { slug: 'fouet', label: 'Fouet' },
  { slug: 'spatule', label: 'Spatule' },
  { slug: 'maryse', label: 'Maryse' },
  { slug: 'couteau', label: 'Couteau' },
  { slug: 'econome', label: 'Économe' },
  { slug: 'rape', label: 'Râpe' },
  { slug: 'passoire', label: 'Passoire' },
  { slug: 'tamis', label: 'Tamis' },
  { slug: 'moule', label: 'Moule' },
  { slug: 'plaque-cuisson', label: 'Plaque de cuisson' },
  { slug: 'papier-cuisson', label: 'Papier cuisson' },
] as const;
